norovirus_url: https://raw.githubusercontent.com/jonathonmellor/norovirus-nowcast/refs/heads/main/outputs/data/cases_with_noise.csv
noro_nowcast_dates:
- '2023-12-10'
- '2024-01-21'
- '2024-02-25'
measles_url: https://raw.githubusercontent.com/kassteele/Nowcasting/refs/heads/master/data/measles_NL_2013_2014.dat
measles_nowcast_dates:
- '2013-07-01'
- '2013-10-01'
- '2014-02-25'
