# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "reference_date", # <get_plot_data_as_of>
  "count", # <get_plot_data_as_of>
  "observed", # <get_plot_data_as_of>
  "as_of_date", # <get_plot_data_as_of>
  "reference_date", # <get_plot_mult_nowcasts>
  "nowcast_date", # <get_plot_mult_nowcasts>
  "q_0.025", # <get_plot_mult_nowcasts>
  "q_0.975", # <get_plot_mult_nowcasts>
  "q_0.25", # <get_plot_mult_nowcasts>
  "q_0.75", # <get_plot_mult_nowcasts>
  "q_0.5", # <get_plot_mult_nowcasts>
  "data_as_of", # <get_plot_mult_nowcasts>
  "observed", # <get_plot_mult_nowcasts>
  "reference_date", # <get_plot_pt_nowcasts>
  "nowcast_date", # <get_plot_pt_nowcasts>
  "predicted", # <get_plot_pt_nowcasts>
  "model", # <get_plot_pt_nowcasts>
  "data_as_of", # <get_plot_pt_nowcasts>
  "observed", # <get_plot_pt_nowcasts>
  "reference_date", # <get_plot_ind_nowcast_draws>
  "total_count", # <get_plot_ind_nowcast_draws>
  "draw", # <get_plot_ind_nowcast_draws>
  "data_as_of", # <get_plot_ind_nowcast_draws>
  "observed", # <get_plot_ind_nowcast_draws>
  "pt_nowcast", # <get_plot_ind_nowcast_draws>
  "reference_date", # <get_plot_ind_nowcast_quantiles>
  "total_count", # <get_plot_ind_nowcast_quantiles>
  "observed", # <get_plot_ind_nowcast_quantiles>
  "data_as_of", # <get_plot_ind_nowcast_quantiles>
  "pt_nowcast", # <get_plot_ind_nowcast_quantiles>
  "q_50", # <get_plot_ind_nowcast_quantiles>
  "q_lb_50th", # <get_plot_ind_nowcast_quantiles>
  "q_ub_50th", # <get_plot_ind_nowcast_quantiles>
  "q_lb_95th", # <get_plot_ind_nowcast_quantiles>
  "q_ub_95th", # <get_plot_ind_nowcast_quantiles>
  "age_group", # <get_plot_bar_chart_sum_scores>
  "model", # <get_plot_bar_chart_sum_scores>
  "overprediction", # <get_plot_bar_chart_sum_scores>
  "underprediction", # <get_plot_bar_chart_sum_scores>
  "dispersion", # <get_plot_bar_chart_sum_scores>
  "value", # <get_plot_bar_chart_sum_scores>
  "pattern", # <get_plot_bar_chart_sum_scores>
  "config", # <get_covid_data>
  "value_>80d", # <get_covid_data>
  "delay", # <get_covid_data>
  "location", # <get_covid_data>
  "report_date", # <get_eval_data_from_long_df>
  "reference_date", # <get_eval_data_from_long_df>
  "count", # <get_eval_data_from_long_df>
  "report_date", # <get_rep_tri_from_long_df>
  "reference_date", # <get_rep_tri_from_long_df>
  "delay", # <get_rep_tri_from_long_df>
  "count", # <get_rep_tri_from_long_df>
  NULL
))
