# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "reference_date", # <get_plot_data_as_of>
  "confirm", # <get_plot_data_as_of>
  "observed", # <get_plot_data_as_of>
  "as_of_date", # <get_plot_data_as_of>
  "reference_date", # <run_baselinenowcast_pipeline>
  "draw", # <run_baselinenowcast_pipeline>
  "total_count", # <run_baselinenowcast_pipeline>
  NULL
))
